# Generated by Django 5.1.7 on 2025-05-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('women', 'Women'), ('men', 'Men')], default='women', max_length=50),
        ),
    ]
