# Generated by Django 5.1.7 on 2025-04-30 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
