<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-30 16:01

=======
# Generated by Django 5.1.7 on 2025-04-30 21:39

import django.db.models.deletion
from django.conf import settings
>>>>>>> 430e1e5bdfc6ce1d5bf8f88cdc9af07ad2550d36
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('products', '0004_remove_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 430e1e5bdfc6ce1d5bf8f88cdc9af07ad2550d36
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
=======
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 430e1e5bdfc6ce1d5bf8f88cdc9af07ad2550d36
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
=======
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
>>>>>>> 430e1e5bdfc6ce1d5bf8f88cdc9af07ad2550d36
            ],
        ),
    ]
